$(document).ready(function(){
  $('.bottom_slider_1').owlCarousel({
     items:3,
      loop:true,
      autoplay:true,
      margin:15,
      responsiveClass:true,
      responsive:{
          0:{
              items:2,
              nav:false
          },
          600:{
              items:2,
              nav:false
          },
          1000:{
              items:3,
              nav:true,
              loop:true
          }
      }
  })
  $('.bottom_slider_2').owlCarousel({
     items:3,
      loop:true,
      autoplay:true,
      margin:15,
      responsiveClass:true,
      responsive:{
          0:{
              items:2,
              nav:false
          },
          600:{
              items:2,
              nav:false
          },
          1000:{
              items:3,
              nav:true,
              loop:true
          }
      }
  })
  $('.bottom_slider_3').owlCarousel({
     items:3,
      loop:true,
      autoplay:true,
      margin:15,
      responsiveClass:true,
      responsive:{
          0:{
              items:2,
              nav:false
          },
          600:{
              items:2,
              nav:false
          },
          1000:{
              items:3,
              nav:true,
              loop:true
          }
      }
  })
  
  $('.past_medical_history').owlCarousel({
     items:1,
      loop:true,
      autoplay:true,
      margin:15,
      responsiveClass:true,
      responsive:{
          0:{
              items:2,
              nav:false
          },
          600:{
              items:2,
              nav:false
          },
          1000:{
              items:3,
              nav:false,
              loop:true
          },
          1200:{
            items:3,
            nav:true,
            loop:true
          }
      }
  })
  
});