$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
       items:3,
        loop:true,
        autoplay:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:2,
                nav:true
            },
            600:{
                items:2,
                nav:true
            },
            1000:{
                items:3,
                nav:true,
                loop:true
            }
        }
    })
  });